commerce_payment.commerce_payment_gateway.plugin.culqi_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    publishable_key:
      type: string
      label: 'Publishable key'
    secret_key:
      type: string
      label: 'Secret key'
    logo:
      type: string
      label: 'Logo'
    maincolor:
      type: string
      label: 'Main Color'
    buttontext:
      type: string
      label: 'Button Text Color'
    maintext:
      type: string
      label: 'Main Text Color'
    desctext:
      type: string
      label: 'Description Text Color'
